spring:
  profiles:
    active: release
  application:
    name: fly-narwhal-server
  datasource:
    url: jdbc:h2:file:./data/fly-narwhal;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  sql:
    init:
      mode: never

server:
  port: 5365
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto

logging:
  # logback.xml配置文件的位置
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.baomidou: DEBUG
    com.jankinwu.flynarwhal.web.mapper: DEBUG

fly-narwhal:
  api-secret: ${FLY_NARWHAL_API_SECRET:16CCEB3D-AB42-077D-36A1-F355324E4237}
